### ISSUE TITLE
Need to translate UKUI

### ISSUE THREAD

**Issue by roxfr** [ukui/community#17]
Hi,
Could you use transifex for translation, please.
Thanks.
Regards,
roxfr

**Comment by handsome-feng** [comment]
Hi, @roxfr , sorry for the delay. We're looking for a good translation platform and will let you know when we find one!

**Comment by roxfr** [comment]
Great :-) Thank you

**Comment by handsome-feng** [comment]
@roxfr Hi, our new translation platform: https://weblate.ubuntukylin.com/

**Comment by roxfr** [comment]
I have just translate ukui-control-center at 100%
