### ISSUE TITLE
debian testing 测试运行 ukui3

### ISSUE THREAD

**Issue by liulitchi** [ukui/community#21]
系统镜像是 debian-testing-amd64-i386-netinst.iso （约650MB），安装后未安装任何桌面环境。直接安装ukui3 ，遇到两个小问题：

1. “菜单”界面左键无法打开（只能右键点击“关机”等操作），为此只能将常用软件的快捷键放在桌面。

2. U盘无法挂载，知道盘符的情况下在终端也无法加载（而用 root 账号登录桌面可以加载U盘）。

除此之外，这个桌面环境非常棒。默认主题非常清爽，期待后续图标美化（比如 retext 和   olive-editor 图标还未美化）。这是一款让人眼前一亮的桌面，十分期待未来发展。

[附图](https://github.com/liulitchi/images/blob/master/debian_testing_ukui.png) [网易云](https://github.com/liulitchi/images/blob/master/debian_ukui_netease.png)

**Comment by handsome-feng** [comment]
1. 终端运行下ukui-menu，看下报什么错？
2. 终端下加载，报什么错呢？

**Comment by liulitchi** [comment]
没想到你们回复得这么快。

> ukui-menu

输出的结果是

```
platform ukui "ukui" ()
platform ukui
create "ukui"
use ukui-white
request icon theme name
dbus[1233]: arguments to dbus_message_new_method_call() were incorrect, assertion "_dbus_check_is_valid_path (path)" failed in file ../../../dbus/dbus-message.c line 1366.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
已放弃
```

**Comment by liulitchi** [comment]
U 盘挂载的情况，debian 软件源添加了 contrib 和 non-free 后，系统重新更新了内核5.6，现在可以完美识别了U盘了。（问题已解决）

**Comment by handsome-feng** [comment]
哦，没注意你只解决了一个问题，开始菜单的问题可能是缺少依赖： sudo apt install accountsservice，你试试？

**Comment by liulitchi** [comment]
哭了，居然显示了，大佬你厉害。

**Comment by handsome-feng** [comment]
:) 我把这个问题关闭了哈
