### ISSUE TITLE
How about rename the repo to community

### ISSUE THREAD

**Issue by imjoey** [ukui/community#4]
Hi there, I notice that this is a project for hosting the community governance stuff, such as the introduction, docs, how to contribute and etc. Honestly speaking, I've considered it as another component, which may be a guide tour application for new users within the UKUI desktop environment. That is because plenty of repositories under UKUI organization are all prefixed with the `ukui-`. 

To avoid the confusion to other contributors, so I was wondering that if we could rename this repository to `community`, which is also an conventional way in many other popular projects like `kubernete/community`, `istio/community` and `ansible/community`.

Looking forward to your insights and the further discussions with you maintainers. Thanks.

**Comment by imjoey** [comment]
Hi @handsome-feng , could you please take a look? Thanks.

**Comment by handsome-feng** [comment]
Hi, Joey, 
You are right, the name would be quite misleading, and I will rename it to community just like other popular projects.
Thanks for your advice!

**Comment by imjoey** [comment]
@handsome-feng  that's great and  really appreciated to you for the opening up and transparency. 😄
